name = "y-partykit-test"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[durable_objects]
bindings = [
  { name = "YPartyKitTestServer", class_name = "YPartyKitTestServer" }
]

[[migrations]]
tag = "v1"
new_classes = ["YPartyKitTestServer"]
